steps:
  - name: docker
    id: build_registry
    entrypoint: sh
    args: 
      - '-c'
      - |
        if [ $_ENV = "staging" ]; then
          docker build -t "eu.gcr.io/ons-eqbs-images/eq-questionnaire-registry:$SHORT_SHA" .
        fi

  - name: docker
    id: push_registry
    entrypoint: sh
    args: 
      - '-c'
      - |
        if [ $_ENV = "staging" ]; then
          docker push "eu.gcr.io/ons-eqbs-images/eq-questionnaire-registry:$SHORT_SHA"
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: tag release
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        if [ $_ENV = "preprod" ]; then
          gcloud container images add-tag \
          eu.gcr.io/ons-eqbs-images/eq-questionnaire-registry:$SHORT_SHA \
          eu.gcr.io/ons-eqbs-images/eq-questionnaire-registry:$TAG_NAME
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    id: deploy_registry
    entrypoint: sh
    args:
      - '-c'
      - |
        if [ $_ENV = "staging" ]; then
          gcloud run deploy eq-questionniare-registry \
          --image "eu.gcr.io/ons-eqbs-images/eq-questionnaire-registry:$SHORT_SHA" \
          --region europe-west2 \
          --platform managed
        else
          gcloud run deploy eq-questionniare-registry \
          --image "eu.gcr.io/ons-eqbs-images/eq-questionnaire-registry:$TAG_NAME" \
          --region europe-west2 \
          --platform managed
        fi
